# Generated by Django 3.2 on 2021-08-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pregunta', models.CharField(max_length=100, verbose_name='Nombre de la pregunta')),
                ('numero_pregunta', models.IntegerField()),
                ('descripcion_pregunta', models.CharField(max_length=200, verbose_name='Nombre de la pregunta')),
                ('imagen_corecta', models.BinaryField(verbose_name='Subir la imagen de Referencia')),
                ('imagen_incorecta1', models.BinaryField(verbose_name='Subir la imagen de Referencia')),
                ('imagen_incorecta2', models.BinaryField(verbose_name='Subir la imagen de Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprende.categoria')),
                ('pregutas', models.ManyToManyField(to='aprende.Pregunta')),
            ],
        ),
    ]
